(function(){
'use strict';
const supabase=window.navodixSupabase;
const type=document.body.dataset.masterCustom;
const isProjects=type==='projects';
let records=[],editingId=null,saving=false,dirty=false;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const table=isProjects?'projects_areas':'action_item_assignees';
function msg(t,type=''){ $('customMasterMessage').textContent=t||''; $('customMasterMessage').className='admin-message'+(type?' '+type:''); }
function fmsg(t,type=''){ $('customMasterFormMessage').textContent=t||''; $('customMasterFormMessage').className='admin-message'+(type?' '+type:''); }
function statusPill(active){return `<span class="status-pill ${active?'status-published':'status-closed'}">${active?'Active':'Inactive'}</span>`;}
async function load(){msg(`Loading ${isProjects?'projects / areas':'assignees'}…`);try{const {data,error}=await supabase.from(table).select('*').order('name');if(error)throw error;records=data||[];render();msg('');}catch(e){console.error(e);msg(`Could not load records: ${e.message||e}`,'error');}}
function render(){const q=$('customMasterSearch').value.trim().toLowerCase(),f=$('customMasterStatus').value;const rows=records.filter(x=>{const hay=isProjects?`${x.name} ${x.description||''}`:`${x.name} ${x.email||''} ${x.mobile||''} ${x.notes||''}`;return (!q||hay.toLowerCase().includes(q))&&(!f||(f==='active'?x.is_active:!x.is_active));});
$('customMasterBody').innerHTML=rows.map(x=>isProjects?`<tr><td><strong class="master-code">${esc(x.name)}</strong></td><td>${esc(x.description||'—')}</td><td>${statusPill(x.is_active)}</td><td>${new Date(x.created_at).toLocaleDateString('en-IN')}</td><td><div class="row-actions"><button class="icon-button" data-action="edit" data-id="${x.id}" title="Edit"><i class="fa-solid fa-pen-to-square"></i></button></div></td></tr>`:`<tr><td><strong class="master-code">${esc(x.name)}</strong></td><td>${esc(x.email||'—')}</td><td>${esc(x.mobile||'—')}</td><td>${statusPill(x.is_active)}</td><td>${esc(x.notes||'—')}</td><td><div class="row-actions"><button class="icon-button" data-action="edit" data-id="${x.id}" title="Edit"><i class="fa-solid fa-pen-to-square"></i></button></div></td></tr>`).join('');
$('customMasterEmpty').classList.toggle('hidden',rows.length>0);$('customMasterBody').closest('.table-wrap').classList.toggle('hidden',rows.length===0);}
function openForm(item=null){editingId=item?.id||null;dirty=false;$('customMasterForm').reset();$('customMasterId').value=editingId||'';$('customMasterTitle').textContent=editingId?(isProjects?'Edit Project / Area':'Edit Assignee'):(isProjects?'Add Project / Area':'Add Assignee');$('customMasterName').value=item?.name||'';$('customMasterActive').value=String(item?.is_active??true);if(isProjects){$('customMasterDescription').value=item?.description||'';}else{$('customMasterEmail').value=item?.email||'';$('customMasterMobile').value=item?.mobile||'';$('customMasterNotes').value=item?.notes||'';}fmsg('');$('customMasterModal').classList.remove('hidden');$('customMasterModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');$('customMasterName').focus();}
function closeForm(force=false){if(!force&&dirty&&!confirm('You have entered information. Are you sure you want to close without saving?'))return;dirty=false;$('customMasterModal').classList.add('hidden');$('customMasterModal').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}
async function save(e){e.preventDefault();if(saving)return;const name=$('customMasterName').value.trim();if(!name){fmsg('Name is required.','error');return;}saving=true;const b=$('saveCustomMaster');b.disabled=true;b.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Saving…';try{let payload={name,is_active:$('customMasterActive').value==='true',updated_at:new Date().toISOString()};if(isProjects)payload.description=$('customMasterDescription').value.trim()||null;else{payload.email=$('customMasterEmail').value.trim()||null;payload.mobile=$('customMasterMobile').value.trim()||null;payload.notes=$('customMasterNotes').value.trim()||null;}const q=editingId?supabase.from(table).update(payload).eq('id',editingId):supabase.from(table).insert(payload);const {error}=await q;if(error)throw error;closeForm(true);msg(editingId?'Record updated successfully.':'Record added successfully.','success');await load();}catch(e){console.error(e);fmsg(`Could not save record: ${e.message||e}`,'error');}finally{saving=false;b.disabled=false;b.innerHTML='<i class="fa-solid fa-floppy-disk"></i> Save';}}
function bind(){$('addCustomMasterButton').addEventListener('click',()=>openForm());$('closeCustomMaster').addEventListener('click',()=>closeForm());$('cancelCustomMaster').addEventListener('click',()=>closeForm());$('customMasterForm').addEventListener('submit',save);$('customMasterForm').addEventListener('input',()=>dirty=true);$('customMasterForm').addEventListener('change',()=>dirty=true);$('customMasterSearch').addEventListener('input',render);$('customMasterStatus').addEventListener('change',render);$('refreshCustomMaster').addEventListener('click',load);$('customMasterBody').addEventListener('click',e=>{const b=e.target.closest('[data-action="edit"]');if(b)openForm(records.find(x=>x.id===b.dataset.id));});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('customMasterModal').classList.contains('hidden'))closeForm();});}
document.addEventListener('DOMContentLoaded',async()=>{bind();const allowed=await window.navodixAdminReady;if(allowed!==false)await load();});
})();
